In [6]:
import pandas as pd
pd.options.display.max_columns = None

In [7]:
df_folds = pd.read_csv('../input/train_folds.csv')
df_folds.head(10)

,id,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,nom_4,nom_5,nom_6,nom_7,nom_8,nom_9,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,day,month,target,kfold
0,242165,0.0,0.0,0.0,F,Y,Blue,Triangle,Axolotl,India,Theremin,85694456d,d892cdc98,a7059911d,a8009baf5,045587877,1.0,Novice,Warm,a,P,TL,5.0,8.0,0,0
1,400150,0.0,0.0,0.0,T,Y,Blue,Trapezoid,Lion,India,Bassoon,a3c2a3216,494b565c1,c79d2197d,d9148f8e7,ed86b6ab9,1.0,Novice,Warm,h,O,JQ,6.0,3.0,0,0
2,159502,0.0,1.0,0.0,T,Y,Blue,Star,NaN,India,Theremin,5bcae230e,c114cc0e0,216083343,dcccc6c19,1ebe4a323,1.0,Expert,Hot,e,O,th,1.0,4.0,0,0
3,72350,0.0,0.0,0.0,F,Y,Red,Square,Lion,Costa Rica,Theremin,fde0ee528,92532bafb,1c756c04a,5859a8a06,b68efd9b1,2.0,Master,Hot,NaN,E,ly,5.0,1.0,1,0
4,113743,0.0,1.0,0.0,F,Y,Red,Triangle,NaN,India,Bassoon,1d0f532e9,88d46d91f,429114096,9f6ed3f30,20d0da77a,3.0,Novice,Cold,a,P,kv,5.0,11.0,0,0
5,18041,0.0,0.0,0.0,F,N,Blue,Triangle,Hamster,Costa Rica,Bassoon,ca60978eb,71337975c,768bc4738,9f6ed3f30,0ec356ef1,1.0,Grandmaster,Boiling Hot,m,X,IS,5.0,3.0,0,0
6,486427,0.0,0.0,1.0,T,N,Red,Triangle,Axolotl,Russia,Theremin,8860ddd20,a0a9e2ada,8c9b654fe,1df855856,28a176921,3.0,Contributor,Warm,k,I,us,1.0,11.0,1,0
7,203135,0.0,0.0,0.0,F,N,Red,Circle,Dog,Russia,Oboe,5e0147702,c79673e7e,3d449d3e8,862d2fbff,ad0597969,1.0,Grandmaster,Freezing,a,C,gt,1.0,8.0,0,0
8,103659,0.0,0.0,0.0,F,Y,Red,Trapezoid,Lion,India,Theremin,0d475c15f,NaN,c5f7d2efd,abce980f5,45d05d91a,2.0,Expert,Freezing,d,K,Mq,1.0,1.0,0,0
9,333982,0.0,0.0,1.0,F,N,Red,Polygon,Hamster,India,Bassoon,6b73116a4,8a1be4396,623908296,fbea9bb4a,5e99ade9b,3.0,Contributor,Cold,k,D,XM,3.0,6.0,0,0

In [8]:
df_folds['kfold'].value_counts()

4    120000
3    120000
2    120000
1    120000
0    120000
Name: kfold, dtype: int64

In [9]:
df_folds.groupby(['kfold'])['target'].value_counts()

kfold  target
0      0         97536
       1         22464
1      0         97536
       1         22464
2      0         97535
       1         22465
3      0         97535
       1         22465
4      0         97535
       1         22465
Name: target, dtype: int64